spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
      auto.register.schemas: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        auto.create.topics.enable: true
        auto.register.schemas: true
      security:
        protocol: PLAINTEXT
    security:
      protocol: PLAINTEXT
  application:
    name: frontdoor
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workers:
      - name: send-payment-worker
        task-queue: payment_subscription
    workersAutoDiscovery:
      packages:
        - com.payments.frontdoor.workflows
        - com.payments.frontdoor.activities
  profiles:
    active: local
server:
  port: 8080
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /api/payments/v1

payments:
  kafka:
    executionTopic: payments.execution.v1

