package com.payments.frontdoor.model;

public enum CrossBoarderActivityType {
    DEBIT, DEBIT_COMPENSATION, RESERVE_CURRENCY, RELEASE_CURRENCY,
    SANCTIONS_CHECK, TRANSFER_TO_CORRESPONDENT, RECALL_FUNDS,
    CREDIT_BENEFICIARY, REFUND_BENEFICIARY
}
