apiVersion: v1
kind: Service
metadata:
  name: frontdoor-service
  labels:
    {{- include "frontdoor-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: frontdoor
