openapi: 3.0.1
info:
  title: Payment Initiation API
  description: API to initiate a simple payment.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/LIAMFORDAU/submit-payent/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://api.example.com
  description: Example API server
paths:
  /api/payments/v1/submit-payment:
    post:
      summary: Initiate a payment
      description: Initiates a simple payment.
      operationId: initiatePayment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
        required: true
      responses:
        "201":
          description: Payment initiated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    PaymentRequest:
      required:
      - amount
      - creditor
      - currency
      - debtor
      type: object
      properties:
        debtor:
          $ref: '#/components/schemas/Account'
        creditor:
          $ref: '#/components/schemas/Account'
        amount:
          type: number
          description: Amount to be transferred
        currency:
          type: string
          description: Currency of the amount
        paymentReference:
          type: string
          description: Reference for the payment
        paymentDate:
          type: string
          description: Date of the payment
          format: date
    Account:
      required:
      - accountNumber
      type: object
      properties:
        accountNumber:
          type: string
          description: Account number
        accountName:
          type: string
          description: Account name
    PaymentResponse:
      type: object
      properties:
        paymentId:
          type: string
          description: Unique identifier for the payment
        status:
          type: string
          description: ISO payment status
          enum:
          - ACTC
          - ACSP
          - ACSC
          - RJCT
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
