name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run JaCoCo Test
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo Test Results
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-test-results
          path: build/jacocoHtml

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontdoor:latest -t ${{ secrets.DOCKER_USERNAME }}/frontdoor:${{ github.sha }} .

      - name: Save Docker image (latest)
        run: docker save ${{ secrets.DOCKER_USERNAME }}/frontdoor:latest -o frontdoor_latest.tar

      - name: Save Docker image (sha)
        run: docker save ${{ secrets.DOCKER_USERNAME }}/frontdoor:${{ github.sha }} -o frontdoor_sha.tar

      - name: Upload Docker image (latest)
        uses: actions/upload-artifact@v3
        with:
          name: frontdoor_latest
          path: frontdoor_latest.tar

      - name: Upload Docker image (sha)
        uses: actions/upload-artifact@v3
        with:
          name: frontdoor_sha
          path: frontdoor_sha.tar

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Docker image (latest)
        uses: actions/download-artifact@v3
        with:
          name: frontdoor_latest

      - name: Download Docker image (sha)
        uses: actions/download-artifact@v3
        with:
          name: frontdoor_sha

      - name: Load Docker image (latest)
        run: docker load -i frontdoor_latest.tar

      - name: Load Docker image (sha)
        run: docker load -i frontdoor_sha.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image (latest)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontdoor:latest

      - name: Push Docker image (sha)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontdoor:${{ github.sha }}

  cleanup:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete old artifacts
        run: |
          gh api -X GET /repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts | sort_by(.created_at) | reverse | .[1:] | .[].id' | xargs -I {} gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/{}

      - name: Delete current Docker artifacts
        run: |
          rm -f frontdoor_latest.tar
          rm -f frontdoor_sha.tar