name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run JaCoCo Test
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo Test Results
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-test-results
          path: build/jacocoHtml

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontdoor:latest -t ${{ secrets.DOCKER_USERNAME }}/frontdoor:${{ github.sha }} .

      - name: Save Docker image
        run: docker save ${{ secrets.DOCKER_USERNAME }}/frontdoor:latest -o frontdoor_latest.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: frontdoor_latest
          path: frontdoor_latest.tar

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: frontdoor_latest

      - name: Load Docker image
        run: docker load -i frontdoor_latest.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontdoor:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontdoor:${{ github.sha }}

  codeql:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Build code
        run: ./gradlew build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2